version: "3.0.0"
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://youruser:yourpassword@cluster.mongodb.net/mydb
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
